#!/bin/bash

## retrieve all of the .go files that have been
## changed since the last commit
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

## check if go files were updated
if [[ $STAGED_GO_FILES != "" ]]; then
    echo "running Git Hook for .go files..."
    for file in $STAGED_GO_FILES; do
        ## format our file
        go fmt $file
        ## add any potential changes from our formatting to the commit
        git add $file
    done
fi
